# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: under construction...
email: kara.e.hannibal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 cortisol and central sensitization - the etiology of chronic pain
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://karahannibal.com" # the base hostname & protocol for your site

<!DOCTYPE html>
<html>
<head>
  <title>Ollie Bike Sharing</title>
  <meta charset="utf-8"/>
  <link rel="stylesheet" type="text/css" href="main.css">
</head>
 <body>
  <div class="container">
  <div class="main">
    <h1>Ollie Bike Sharing</h1>
  <h3>Share Your Pedals with the World.</h3>
<p>Need a set of wheels while you're in town? Use Ollie to pair your perfect vacation with a stylish, affordable bike rental. Here is a list of cities where you can find us.</p>

  <a href="cities.html">list</a>
  <video width="320" height="240" controls>
  <source src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-1/ollie.mp4" type="video/mp4">
</video>
   </div>
 <div class="nav"> 
  <h2>Ollie</h2>
  <ul>
  <li>sign up</li>
  <li>search bikes</li>
  <li>reserve a bike</li>
  <li>about us</li>
</ul>
    </div>
   </div>
  </body>
</html>

# Build settings
markdown: kramdown
